# Generated by Django 5.1.6 on 2025-02-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
