# Generated by Django 5.1.6 on 2025-02-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_adminuser_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Admins', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='updated_by',
            field=models.CharField(blank=True, default='Null', max_length=255, null=True),
        ),
    ]
