# Generated by Django 5.1.6 on 2025-02-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_blacklisttoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklisttoken',
            old_name='created_at',
            new_name='blacklisted_at',
        ),
        migrations.AlterField(
            model_name='blacklisttoken',
            name='token',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
