# Generated by Django 5.1.6 on 2025-02-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_created_at_blacklisttoken_blacklisted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklisttoken',
            old_name='blacklisted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='blacklisttoken',
            name='token',
            field=models.TextField(unique=True),
        ),
    ]
