# Generated by Django 5.1.6 on 2025-02-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_blacklisted_at_blacklisttoken_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklisttoken',
            old_name='created_at',
            new_name='blacklisted_at',
        ),
    ]
