# Generated by Django 5.1.6 on 2025-02-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_created_at_blacklisttoken_blacklisted_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistToken',
        ),
    ]
