# Generated by Django 5.1.6 on 2025-03-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_delete_blacklisttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='last_login',
            field=models.DateTimeField(blank=True, default='Null', null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='updated_at',
            field=models.DateTimeField(blank=True, default='Null', null=True),
        ),
    ]
