# Generated by Django 5.1.6 on 2025-03-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_adminuser_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
