# Generated by Django 5.1.6 on 2025-03-09 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_adminuser_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(default='inactive', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeltTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('belt_device_name', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=255, unique=True)),
                ('uuid', models.CharField(max_length=255)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('device_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='disconnected', max_length=13)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
        ),
        migrations.CreateModel(
            name='BatteryMonitoring',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('battery_percentage', models.IntegerField()),
                ('threshold', models.IntegerField(default=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alarm_time', models.DateTimeField()),
                ('status', models.CharField(default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
        ),
    ]
