# Generated by Django 5.1.6 on 2025-03-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_user_belttracking_batterymonitoring_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='user',
        ),
    ]
