# Generated by Django 5.1.6 on 2025-03-09 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_alarm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='alarm_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batterymonitoring',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
        migrations.AlterField(
            model_name='belttracking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
    ]
