# Generated by Django 5.1.6 on 2025-03-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alarm_user_alter_alarm_alarm_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batterymonitoring',
            name='battery_percentage',
        ),
        migrations.AddField(
            model_name='batterymonitoring',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
