# Generated by Django 5.1.6 on 2025-03-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_batterymonitoring_battery_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='belttracking',
            old_name='belt_device_name',
            new_name='belt_name',
        ),
    ]
